### ISSUE TITLE
HomeSeer.Jui.Views.InputView: Error - ArgumentOutOfRangeException [Cases not defined]

### ISSUE THREAD

**Issue by russr999** [HomeSeer/Plugin-SDK#104]
Environment and System Config

OS: Windows
Language: VB
IDE: VS2019
HomeSeer Version: v4.1.0.0
PluginSDK Version: v1.2.0.0
Describe the issue
When using HomeSeer.Jui.Views.InputView and type = EInputType.Date it throws an error : _ArgumentOutOfRangeException_

This error is true for types:
- date
- datetime
- time

The function (public override string ToHtml )in the Plugin-SDK: Plugin-SDK/Jui/Views/InputView.cs is where the error is being thrown as the 3 types above are not allowed for the the CASE inputs. (Lines 158 - 180)

Can the plugin-SDK be updated to include the 3 EInputTypes above please?

Thanks

**Comment by jldubz** [comment]
Tracked by internal ticket PSDK-218. 

Thanks for bringing this up. This was delayed due to a need to track seconds in the time picker. No reason a version of it without seconds can't be added until then. We will work on implementing this using the mdbootstrap date and time pickers.
* https://mdbootstrap.com/docs/b4/jquery/forms/date-picker1/
* https://mdbootstrap.com/docs/b4/jquery/forms/time-picker1/

**Comment by jldubz** [comment]
We added `EInputType.Date` and `EInputType.Time` in [v1.4.0.0](https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_4_0_0.html)
