### ISSUE TITLE
EMiscFlag.Hidden not honored

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#109]
Version 4.1.1.0

Two Issues.  
#1 Devices and Features with MISC property Hidden set continue to be displayed
#2 Setting MISC property using AddMiscFlag only changes local copy and does not persist to the Device

#1 
Feature with Misc Flag Hidden (32) set continues to be displayed in tile and list views
Device with Misc Flag Hidden (32) set continues to be displayed in tile and list views
Device with 4 features, all 5 items having Misc Hidden (32) set show in /deviceutility.  This is how I confirmed all Hidden Misc flags set

#2 
When setting the Hidden flag using the following I confirmed with Visual Studio that uMisc had Hidden bit set (misc = 288), but when viewing the device with /deviceutility the misc property was 256.  
            oDevice.AddMiscFlag(HomeSeer.PluginSdk.Devices.EMiscFlag.Hidden)
            Dim uMisc As UInt32 = oDevice.Misc

To make the flag persist the following had to be appended to the above
            hs.UpdatePropertyByRef(iParentRef, Devices.EProperty.Misc, uMisc)

**Comment by spudwebb** [comment]
1. Tested with 4.1.9.0: 
it works for me in list view, but you still have to click the "eye" button for the features to be displayed.
it doesn't work in grid view: nothing is hidden but I'm not sure what is the expected behavior there.
Can you confirm this is what you experience too?

2. This is the expected behavior, you have to call UpdatePropertyByRef for a change to be sent to HS4. More info here: https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-plugin-development/1434132-abstracthsdevice-vs-hs-getpropertybyref?p=1434414#post1434414
