### ISSUE TITLE
Error sending message: Type 'HomeSeer.Jui.Views.InvalidValueForTypeException' in Assembly 'PluginSdk' is not marked as serializable.

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#129]
**Environment and System Config**
- OS: N/A
- Language: C#
- IDE: N/A
- HomeSeer Version: [v4.1.10.0]
- PluginSDK Version: [v1.2.1.0]

**Describe the issue**
All Exceptions thrown during processing requests from HS should be marked Serializable

**Steps to Reproduce**
Cause any exception, i.e. create an InputView(EInputType.Url) and pass string which is not a url

**Expected behavior**
The exception should be displayed to user

**Comment by spudwebb** [comment]
Did you try to mark the exception as serializable and if so, was it then displayed to the user?
I think this issue is more complicated than that, and the underlying problem is that exceptions (even if marked Serializable) are not propagated through HSCF,  Tracked as HS-1083.

> HomeSeer Version: [v4.0.0.30]
> PluginSDK Version: [v1.0.6.0]
are you really testing with those versions ? if so you should update.

**Comment by alexbk66** [comment]
No, I'm on latest versions, sorry, that's default when you create an issue
HomeSeer Version: [v4.1.10.0]
PluginSDK Version: [v1.2.1.0]

**Comment by spudwebb** [comment]
It turns out we need to mark the exception Serializable and add a special constructor for HSCF to be able to deserialize it:

`        protected InvalidValueForTypeException(SerializationInfo info, StreamingContext context) : base(info, context) { }`'

I fixed it as part of PSDK-117. It should be in the next SDK release.

**Comment by alexbk66** [comment]
Thank you.  I tried to mark the exception Serializable - then the error isn't shown at all, but at least the plugin doesn't crash.
I added exception handler and instead of displaying the offending view - I add a lable with the error info. Do you have mechanism for displaying errors in the settings pages?

**Comment by spudwebb** [comment]
Fixed in Plugin SDK version 1.2.2
