### ISSUE TITLE
 GetTriggersByType and TriggerFire documentation confusing

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#141]
@spudwebb,@rjhdakota 

GetTriggersByType says the first parameter is Name, TriggerFire says the first parameter is ID

The sample vb project uses Name as the both (i guess because the sample is actually the same)

is the documentation wrong?

**Comment by spudwebb** [comment]
I think you're right, currently yo need to pass the plugin name for those functions to work. Tracked as PSDK-120

**Comment by mnsandler** [comment]
can you verify GetTriggersByType  wants Name while TriggerFire wants ID

both seem to work a expected using the properties I identified here

for my plugin name = "Insteon Plugin" and ID = "Insteon"

so i know they both aren't expecting Name nor ID

**Comment by mnsandler** [comment]
@spudwebb  did you update GetTriggersByType to expect Id instead of Name for the first parameter?

same question for UpdatePlugTrigger

**Comment by spudwebb** [comment]
No, this is not fixed yet, and as mentioned in other issues for now you should use the same thing for plugin ID and Name.
Once this is fixed the goal is for all those functions to work with plugin ID instead of plugin name as parameters.

**Comment by mnsandler** [comment]
ok. thanks. fell free to close this if you already have an open bug ticket on the same issue

**Comment by spudwebb** [comment]
This has been fixed in HS 4.1.14.0 and the inline documentation has been fixed in PluginSdk 1.2.3.
Now you should always pass the plugin ID instead of the plugin Name to methods that  manipulate triggers and actions.

If you are using a plugin Id different from the plugin name, and if your plugin implements some triggers please update your plugin code ASAP as it will no longer work with HS 4.1.14.0
