### ISSUE TITLE
There is still an issue between when hs4 uses the ID and Name properties.

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#163]
@spudwebb 

When i have Name = 'Insteon Plugin', and ID = 'Insteon'

the event definition doesn't show my actions as being configured when my plugin is running. ie plugin not running message

if I change prop Name = 'Insteon' then everything works fine

something internal is using Name instead of ID

as far as I'm concerned, Name should only be used for UI display purposes, not as in internal Key; that is what ID is for

**Comment by spudwebb** [comment]
I agree, 
HS4 mistakenly uses the plugin name instead of the plugin ID to save plugin actions and triggers.  We are working on it but it's not fixed yet, so right now just use ID = Name = Insteon

**Comment by spudwebb** [comment]
This has been fixed in HS 4.1.14.0 and the inline documentation has been fixed in PluginSdk 1.2.3.
Now you should always pass the plugin ID instead of the plugin Name to methods that manipulate triggers and actions.

If you are using a plugin Id different from the plugin name, and if your plugin implements some triggers please update your plugin code ASAP as it will no longer work with HS 4.1.14.0
