### ISSUE TITLE
Internet Explorer is not supported?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#180]
Most functionality doesn't work in IE11

**Comment by gmitch64** [comment]
IE11 goes End of Life, and support ends on August 17th 2021, so I don't know if it's going to be worth spending much time fixing any IE11 issues?

G

**Comment by brientim** [comment]
Even though IE11 is due for EoL later this year, there are still users that use IE11 or are are older operating systems, I am not one, but still test based on commonly used browsers including Safari, IE11 including in compatibility modes, Edge, Edge Chromium and Chrome and sometime Firefox.  

Effectively if this defect is not rectified, HST should declare a declaimer that HS4 is has known compatibility issues with IE11 and may not work or HS4 is not supported on IE11.  In addition, this means that the developers will needs to test and declare similar compatibility statement. That may influence whether or not people would purchase or upgrade to HS4 and/or whether they would buy a HS4 plugin or run older versions which maintains compatibility and are current functional.

**Comment by alexbk66** [comment]
I agree, if HS4 doesn't work - HST should say so t the users.  And inform developers.

**Comment by rjhdakota** [comment]
We can note this. HS4 is based on the Bootstrap framework and Bootstrap does not support IE11 so the ability to support IE11 is out of our control.

**Comment by alexbk66** [comment]
> We can note this. HS4 is based on the Bootstrap framework and Bootstrap does not support IE11 so the ability to support IE11 is out of our control.

You should've said so.  I'm getting complains from users, I investigate what's wrong - time wasting.

**Comment by brientim** [comment]
> We can note this. HS4 is based on the Bootstrap framework and Bootstrap does not support IE11 so the ability to support IE11 is out of our control.

Even though Bootstrap 5 itself drop IE 11/10 Compatibility there are a number of polyfills workarounds that negates this and could be embedded into the HS4 SDK framework rather than individual developers discovering this or implementing their own policies.

The problem is that individuals may not upgrade and they will expect the individual developers to provide fixers or support. Remembering that not all developers have the ability to test on all platforms and Browsers and therefore, the alternative is to declare this in the SDK that HS4 employs Bootstrap 5 framework and HS4 does not support Internet Explorer and it is recommended to upgrade to a modern browser, Edge, Chrome, Firefox, Pale Moon etc...

Example of Work Around 
https://themesberg.com/blog/bootstrap/bootstrap-5-ie-11-browser-support
https://coliff.github.io/bootstrap-ie11/
