### ISSUE TITLE
Can't create status only device?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#187]
I created new virtual device, but can't change Status/Controls to status only

![image](https://user-images.githubusercontent.com/2533315/112740736-3e392e80-8fcb-11eb-9d06-6b310695fcf0.png)

**Comment by alexbk66** [comment]
Is Control/Status selector available for HS3 devices only?

![image](https://user-images.githubusercontent.com/2533315/112740785-8f492280-8fcb-11eb-9d36-4a889850867b.png)

**Comment by spudwebb** [comment]
Yes, you can't change a StatusControl to status only for a HS4 device, this is intended. If you want a status only range or single value for a HS4 device, just create a StatusGraphic which by definition are always status only.

The "Edit Status/Control" section for a HS4 device will be rename to "Edit Controls" because you should only define real controls in there.

**Comment by alexbk66** [comment]
But the second screenshot shows Status only?

**Comment by spudwebb** [comment]
the second screenshot is a HS3 device, it is still allowed for a HS3 device.

**Comment by alexbk66** [comment]
Ok, thank you.

Can you also please have a look (asap) at https://github.com/HomeSeer/Plugin-SDK/issues/186
