### ISSUE TITLE
20 is not valid for this graphic Parameter name: value

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#205]
- HomeSeer Version: [v4.1.17.0]
- PluginSDK Version: [v1.3.0.0]

What's the motivation for adding new ArgumentOutOfRangeException in GetLabelForValue?

Do you realise that by adding the exception you break the **interface** and break the code?

Why not just return null?

**Comment by alexbk66** [comment]
I see there's now TryGetLabelForValue?  Which mostly duplicates GetLabelForValue.  

It looks wrong that GetLabelForValue has three calls to ReplaceAdditionalData, but TryGetLabelForValue - only two calls?

**Comment by spudwebb** [comment]
The  ArgumentOutOfRangeException is in  GetLabelForValue (and is documented)  since version 1.0.0.0 of the PluginSdk, so not sure what you are complaining about. If it does not behave as expected please provide a test case.

GetLabelForValue  could be simplified to have only two calls to ReplaceAdditionalData, but that would not changed its behavior.

**Comment by alexbk66** [comment]
Hmm, it started to throw the Exception after the update to v4.1.17.0 / v1.3.0.0.
Before was working fine.  Not sure what's happening here, need to dig deeper.
