### ISSUE TITLE
HS4 Web Server returning 404 when POST sent to unregistered pages

### ISSUE THREAD

**Issue by sjhill01** [HomeSeer/Plugin-SDK#216]
I have some pages I don't want to show up in the menu but only use in the background. At some point a change in HS4 (sorry, not sure which - I'm running 4.2.0.0 on my production system) made it so that POSTs to those pages return 404 errors. GETs work fine, but PostBackProc is never called and the browser console shows a 404 on ajax calls. This has broken my Lyric plugin and my in-progress DeviceHistory plugin.

**Comment by spudwebb** [comment]
You're correct, it has been changed in 4.2.0.0 : If a POST is made to a .html page, HS4 checks that this page is registered, if not a 404 is returned.
However you can still POST to a non registered page if this page doesn't have an extension. So for endpoints you don't want an entry to show up in the menu, just use /MyPlugin/test instead of /MyPlugin/test.html, and the PostBackProc function in your plugin will be called.

**Comment by spudwebb** [comment]
sorry for the lack of communication, we should have warned developers about this change.
