### ISSUE TITLE
will an hs3 plugin call to another hs3 plugin work between hs3 - Hs4 plugins

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#235]
my insteon plugin has an API for others plugins to use. this all works fine in HS3

should this continue to work after i upgrade my insteon plugin to HS4 while the calling plugin is still HS3?

would the following old code still work to call a method in an hs4 plugin:

```
    Public Function PluginFunction(ByVal proc As String, ByVal parms() As Object) As Object Implements IPlugInAPI.PluginFunction

        Try
            Dim ty As Type = Me.GetType
            Dim mi As MethodInfo = ty.GetMethod(proc)

            If mi Is Nothing Then
                Log("Method " & proc & " does not exist in this plug-in.", LogLevel.Errors)
            Else
                Return (mi.Invoke(Me, parms))
            End If

        Catch ex As Exception
            Log("Error in PluginProc: " & ex.Message, LogLevel.Errors)
        End Try

        Return Nothing

    End Function
```

**Comment by spudwebb** [comment]
your HS4 plugin HSPI class inherit the method defined in AbstractPlugin:

```csharp
        public object PluginFunction(string procName, object[] @params) {
            try {
                var ty = GetType();
                var mi = ty.GetMethod(procName);
                return mi == null ? null : mi.Invoke(this, @params);
            }
            catch (Exception exception) {
                if (LogDebug) {
                    Console.WriteLine(exception.Message);
                }
            }

            return null;
        }
```

so any plugin (HS3 or HS4) can call methods defined in your HSPI class using `IHsController.PluginFunction` or whatever was the equivalent in the HS3 API

**Comment by mnsandler** [comment]
@spudwebb thanks for the quick reply. so the call should look something like

hs.pluginfunction("pluginid", "procName", "parms")

this should be the same in hs3 as in hs4

i dont understand why it isn't working

so i dont understand why it isn't working from an old hs3 plugin to a new hs4 plugkn.

**Comment by jldubz** [comment]
@mnsandler,

> so i dont understand why it isn't working from an old hs3 plugin to a new hs4 plugkn.

Sorry for any confusion here. HS3 plugins do not know about any HS4 features. The reason why is because the HS3 plugin calls are routed through legacy code which has no knowledge of HS4 plugins. This is because the HS3 Plugin API is being discontinued. No more enhancements will be made to it, which includes handling routing to and communication with HS4 plugins. The HS3 Plugin API will only receive patches to critical/blocking issues for the time being.

These HS3 plugins that are communicating with your HS4 plugin can continue to use the HS3 plugin version, but they will need to be migrated to HS4 to integrate with your HS4 plugin.

**Comment by jldubz** [comment]
@mnsandler, Thank you for understanding. I am going to close this issue, but if there is anything else we can do to help please feel free to ping me and reopen it.
