### ISSUE TITLE
EProperty.FeatureDisplayType not supported

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#315]
HS 4.2.14.0

When executing the following code

Dim oType As HomeSeer.PluginSdk.Devices.EFeatureDisplayType = CType(hs.GetPropertyByRef(9983, HomeSeer.PluginSdk.Devices.EProperty.FeatureDisplayType), HomeSeer.PluginSdk.Devices.EFeatureDisplayType)

The console response is

Exception deserializing message: Unable to load type Scheduler.Classes.Model.Devices.PriorityDisplayType required for deserialization.

and timeout occurs before statement returns

**Comment by spudwebb** [comment]
You are testing this by starting your plugin remotely right?
I can reproduce this exception by adding your line of code to the sample plugin and running it remotely from visual studio. but if I install the same modified sample plugin in the HomeSeer directory, the exception disappear.
I will log it as a bug nonetheless, but a simple workaround for now is to copy Scheduler.dll into your output directory so that it works even when run remotely.

**Comment by mcsSolutions** [comment]
Thank You.  That solves the problem.  Should the general practice be to include the HS3 dll’s in my updater package so others that may be running remotely will not run into the issue?

**Comment by spudwebb** [comment]
No you should not include Scheduler.dll in your updater package. The plugin SDK was designed so that PluginSdk.dll and HSCF.dll are the only 2 homeseer dependencies needed to run a HS4 plugin. This is  not the case here, but we can fix it on HS side. 
Tracked as HS-1708
