### ISSUE TITLE
Unable to get Input Text in Action OnConfigItemUpdate

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#63]
Similar to issue #57 

When evaluating user input for action setup in  OnConfigItemUpdate on a new action the textbox input always returns null after the SAVE icon clicked.  OnConfigItemUpdate  method is not entered following CR after the text box data has been completed to provide an earlier evaluation attempt.

In the code below sMessage is always null.  It is also null when using sMessage = 
 ConfigPage.GetViewById(ActionInputId).GetStringValue.  Since the text box input needs to be evaluated for validity before the action is saved either no validity is performed or the event can never be saved successfully.

`Protected Overrides Function OnConfigItemUpdate(ByVal configViewChange As AbstractView) As Boolean
        Dim selectList As SelectListView = TryCast(ConfigPage.GetViewById(ActionTypeSelectListId), SelectListView)
        Dim iActionType As Integer = selectList.Selection
        Dim inputView As InputView = TryCast(ConfigPage.GetViewById(ActionInputId), InputView)
        Dim sMessage As String = inputView.GetStringValue

        Dim changedActionType As SelectListView = TryCast(configViewChange, SelectListView)
        If changedActionType IsNot Nothing Then
            'change made to the selector?
            If selectList.Selection <> changedActionType.Selection AndAlso selectList.Selection <> -1 Then
                ConfigPage = InitNewConfigPage(changedActionType.Selection).Page
                Return False
            End If
        End If
        With New System.Text.StringBuilder
            If iActionType = 0 Then
                'send mqtt message
                Dim i As Integer = InStr(sMessage, "=")
                If i = 0 Then
                    ConfigPage = InitConfigPageWithFeedback("No action will be performed because message not entered as Topic=Payload").Page
                    Return False
                End If
            ElseIf iActionType = 1 Then
                'publist
                If Not System.IO.File.Exists(gDataPath & sMessage & ".pub") Then
                    ConfigPage = InitConfigPageWithFeedback("Publist publication list " * sMessage & " will not execute as an event action until " & sMessage & " is created.").Page
                    Return True
                Else
                End If
            End If
        End With

        Return True

    End Function`

**Comment by jldubz** [comment]
In your code sample, I am not seeing where you are evaluating the configViewChange when it is the input view.  The value of the view on the page is not saved until OnConfigItemUpdate returns TRUE; so querying it with `sMessage = inputView.GetStringValue` will absolutely always return nothing.  You should be looking at `sMessage = configViewchange.GetStringValue` for the new value of the input view just like you are doing when you cast configViewChange to a SelectListView and determine what has been selected.

I'm going to close this issue because there isn't an action item to track in terms of the development of the SDK, but I will still answer further questions on the subject in the comments here.

**Comment by mcsSolutions** [comment]
sMessage = configViewchange.GetStringValue  addresses the issue.
