### ISSUE TITLE
Long Delays between Connect and initial call to plugin to initialize

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#87]
Version 4.0.4.0
HS3 plugin, observed in mcsMQTT and mcsHubitat

HS4 install is a test install with no events and minimum number of devices.  The log segment below reflects one instance of of mcsMQTT being started from Visual Studio on same PC as HS4.  It shows a period of over 5 minutes (7:56 PM to 8:01 PM) between when the plugin connects to HS4 and when HS4 calls InitIO() of the plugin.

Is there some internet dependency that exists between connect and initial call?  Other users have posted on Message Board of intermittent behavior of being able to initiate the plugin.  It generally starts in a matter of seconds, but at times it does not.  During development if the initialization does not occur immediately then I will normally restart HS/Plugin etc to get back to normal response times.  This is an example where I just waited and it eventually did call back to the plugin to initialize.

From
Type
Message
4/3/2020 8:03:02 PM
HomeSeer
Error
Saving database: Value cannot be null.
Parameter name: collection
4/3/2020 8:02:01 PM
HomeSeer
Error
Saving database: Value cannot be null.
Parameter name: collection
4/3/2020 8:01:28 PM
HomeSeer
Starting Plug-In
Plugin mcsMQTT started successfully in 13269 milliseconds
4/3/2020 8:01:27 PM
Legacy-Plugin
mcsMQTT
Version 5.2.3.2 Registered with Homeseer 
4/3/2020 8:01:14 PM
HomeSeer
Starting Plug-In
Initializing plugin mcsMQTT ...
4/3/2020 7:55:56 PM
HomeSeer
Info
Plugin mcsMQTT has connected. IP:127.0.0.1:53760

**Comment by spudwebb** [comment]
This can happen when one InitIO call fails, for example your InitIO throws an exception, in this case HS4 tries to call ShutdownIO but since the plugin has already disconnected, it gets stuck until the remote call times out (8 minutes). This results in all subsequent plugin start to be delayed until the previous ShutdownIO has timed out.

This is a bug, HS4 should not get stuck in ShutdownIO for 8 minutes but should return immediately when the plugin has already  disconnected. This is tracked as HS-883

**Comment by spudwebb** [comment]
Fixed in HS 4.1.11.0
